name: Hello Evan
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21226583374664187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#4e697f'
    - '#283c58'
    - '#9c917c'
    - '#ebcda0'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
