name: Hello Evan
favicon: null
layout_spectrum: 0.4609656734392047
typography_spectrum: 0.21226583374664187
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2650449965149164
  lightness: 0.5476282332092524
  saturation: 0.7098429328761995
  rhythmicContrast: 0.5454339205753058
purpose: []
